import turtle

wn = turtle.Screen()
wn.bgcolor("black")
wn.title("integral_alıcı")

tosbaga = turtle.Turtle()  # kaplumbağa oluşturduk
tosbaga.color("white")
tosbaga.pensize(2)
tosbaga.speed(2)

def direnc():
    tosbaga.forward(10)
    tosbaga.left(60)
    tosbaga.forward(5)
    tosbaga.right(130)
    for i in range(2):
        tosbaga.forward(10)
        tosbaga.left(140)
        tosbaga.forward(10)
        tosbaga.right(140)
    tosbaga.forward(10)
    tosbaga.left(140)
    tosbaga.forward(5)
    tosbaga.right(70)
    tosbaga.forward(10)

def opamp():
    tosbaga.forward(20)
    tosbaga.left(90)
    tosbaga.forward(20)
    tosbaga.right(120)
    tosbaga.forward(60)
    tosbaga.right(120)
    tosbaga.forward(60)
    tosbaga.right(120)
    tosbaga.forward(40)
    tosbaga.backward(20)

def gnd():
    tosbaga.left(90)
    tosbaga.forward(20)
    tosbaga.left(90)
    tosbaga.forward(40)
    tosbaga.right(90)
    tosbaga.forward(10)
    tosbaga.backward(20)
    tosbaga.forward(10)
    #print(tosbaga.position())
    tosbaga.penup()
    tosbaga.left(90)
    tosbaga.forward(5)
    tosbaga.position()
    tosbaga.right(90)
    tosbaga.forward(5)
    tosbaga.pendown()
    tosbaga.backward(10)

    tosbaga.penup()
    tosbaga.left(90)
    tosbaga.forward(5)
    tosbaga.position()
    tosbaga.right(90)
    tosbaga.forward(2.5)
    tosbaga.pendown()
    tosbaga.forward(5)

def geribes():
    tosbaga.penup()
    tosbaga.setposition(-256, 120)
    tosbaga.right(180)
    direnc()
    tosbaga.pendown()
    tosbaga.left(90)
    tosbaga.forward(60)
    tosbaga.right(90)
    tosbaga.forward(40)
    tosbaga.left(90)
    tosbaga.forward(10)
    tosbaga.backward(20)
    tosbaga.forward(10)

    tosbaga.penup()
    tosbaga.position()
    tosbaga.right(90)
    tosbaga.forward(10)
    tosbaga.pendown()
    tosbaga.left(90)
    tosbaga.forward(10)
    tosbaga.backward(20)
    tosbaga.forward(10)
    tosbaga.right(90)
    tosbaga.forward(40)
    tosbaga.right(90)
    tosbaga.forward(70)
    tosbaga.right(90)
    tosbaga.forward(20)
    tosbaga.backward(60)
    tosbaga.right(180)

def integral_alan(tosbaga):
    tosbaga.penup()
    tosbaga.setposition(-256, 120)
    tosbaga.pendown()
    direnc()
    opamp()
    gnd()
    geribes()
integral_alan(tosbaga)

wn.mainloop()